
name: Deploy with Vite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci || npm install
        npm list --depth=0
    
    - name: Setup environment
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Working directory: $(pwd)"
        echo "Directory contents: $(ls -la)"
    
    - name: Build
      run: npm run build
      env:
        CI: false
      
    - name: Verify build output
      run: |
        echo "Build directory contents:"
        ls -la dist || echo "dist directory not found"
        if [ ! -d "dist" ]; then
          echo "Error: dist directory was not created during build"
          exit 1
        fi
      
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: dist-files-${{ matrix.node-version }}
        path: dist
        retention-days: 5
    
    - name: Set up JDK and Kotlin for Android builds
      if: false  # Only enable this step when building Android
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        kotlin-version: '1.8.22'

